"$schema" = "./node_modules/wrangler/config-schema.json"
name = "wk-cfnew-auto-update"
main = "_worker.js"
compatibility_date = "2026-01-20"
workers_dev = false

#[vars]
#et= "yes"
#et = "yes"
#ex = "yes"
#ech = "yes"
#ae = "yes"


[[kv_namespaces]]
binding = "C"
id = "753fa16245ec455fafb1bd8a05e830c3"
